// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQjsb5eeUF9L-fo56NQdbgEpzafSiMJaI',
    appId: '1:524518799350:web:f6819dd8ab283040fb39d7',
    messagingSenderId: '524518799350',
    projectId: 'thigk-bcde1',
    authDomain: 'thigk-bcde1.firebaseapp.com',
    databaseURL: 'https://thigk-bcde1-default-rtdb.firebaseio.com',
    storageBucket: 'thigk-bcde1.firebasestorage.app',
    measurementId: 'G-T4HQWCMEW8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIlsDdtowLH-lBsO_Af9s-QsTdReB5qjE',
    appId: '1:524518799350:android:511b8e94c867712ffb39d7',
    messagingSenderId: '524518799350',
    projectId: 'thigk-bcde1',
    databaseURL: 'https://thigk-bcde1-default-rtdb.firebaseio.com',
    storageBucket: 'thigk-bcde1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAnSZC3kyH9iWDDo8It0u32I_vBgc2Gn8',
    appId: '1:524518799350:ios:04a641fca2a4cb3dfb39d7',
    messagingSenderId: '524518799350',
    projectId: 'thigk-bcde1',
    databaseURL: 'https://thigk-bcde1-default-rtdb.firebaseio.com',
    storageBucket: 'thigk-bcde1.firebasestorage.app',
    iosBundleId: 'com.example.giuaKy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAnSZC3kyH9iWDDo8It0u32I_vBgc2Gn8',
    appId: '1:524518799350:ios:04a641fca2a4cb3dfb39d7',
    messagingSenderId: '524518799350',
    projectId: 'thigk-bcde1',
    databaseURL: 'https://thigk-bcde1-default-rtdb.firebaseio.com',
    storageBucket: 'thigk-bcde1.firebasestorage.app',
    iosBundleId: 'com.example.giuaKy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQjsb5eeUF9L-fo56NQdbgEpzafSiMJaI',
    appId: '1:524518799350:web:eb041945bd36318ffb39d7',
    messagingSenderId: '524518799350',
    projectId: 'thigk-bcde1',
    authDomain: 'thigk-bcde1.firebaseapp.com',
    databaseURL: 'https://thigk-bcde1-default-rtdb.firebaseio.com',
    storageBucket: 'thigk-bcde1.firebasestorage.app',
    measurementId: 'G-CQ686QQ8KP',
  );
}
